name: Build and Push Image

on:
    push:
      paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
      tags:
        - "**"
      branches:
        - 'main'
        - 'release/version*'
        - 'docker-images'
    workflow_dispatch:
jobs:
  call-reusable-workflow:
    uses: nationalsecurityagency/datawave/.github/workflows/microservice-build-image.yaml@integration
    secrets:
      USER_NAME: ${{ secrets.USER_NAME }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}