name: Run Maven Tests

on:
  push:
    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
    branches:
    - 'main'
    - 'release/*'
  pull_request:
    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']

jobs:
  call-reusable-workflow:
    uses: nationalsecurityagency/datawave/.github/workflows/microservice-maven-tests.yaml@integration